// 교회 수련회 성경 퀴즈 문제 은행 (중고등부)
const CHURCH_QUIZ_DATA = [

  // ── 창세기 / 창조 ──────────────────────────────
  { question: '하나님이 세상을 창조하신 날은 며칠인가요?',
    options: ['4일', '5일', '6일', '7일'], correctIndex: 2 },
  { question: '에덴동산에서 아담과 하와를 유혹한 동물은?',
    options: ['사자', '뱀', '여우', '독수리'], correctIndex: 1 },
  { question: '하나님이 아담의 무엇으로 하와를 만드셨나요?',
    options: ['손톱', '갈비뼈', '머리카락', '눈물'], correctIndex: 1 },
  { question: '가인이 죽인 사람은 누구인가요?',
    options: ['야벨', '셋', '아벨', '에녹'], correctIndex: 2 },
  { question: '노아 홍수 때 비가 내린 기간은?',
    options: ['20일 밤낮', '30일 밤낮', '40일 밤낮', '50일 밤낮'], correctIndex: 2 },
  { question: '노아가 방주에서 처음으로 내보낸 새는?',
    options: ['비둘기', '독수리', '까마귀', '참새'], correctIndex: 2 },
  { question: '아브라함이 이삭을 제물로 바치려 한 산은?',
    options: ['시내산', '모리아산', '올리브산', '갈멜산'], correctIndex: 1 },
  { question: '야곱이 낳은 아들은 모두 몇 명인가요?',
    options: ['10명', '11명', '12명', '13명'], correctIndex: 2 },
  { question: '요셉의 형제들이 요셉을 판 값은?',
    options: ['은 10냥', '은 20냥', '은 30냥', '은 40냥'], correctIndex: 1 },
  { question: '야곱이 하나님과 씨름한 후 새로 받은 이름은?',
    options: ['이삭', '이스라엘', '아브라함', '모세'], correctIndex: 1 },
  { question: '아브라함의 원래 이름은?',
    options: ['아브람', '야곱', '이삭', '롯'], correctIndex: 0 },
  { question: '에서와 야곱 중 먼저 태어난 사람은?',
    options: ['야곱', '에서', '동시에 태어났다', '알 수 없다'], correctIndex: 1 },
  { question: '하나님이 노아와 맺은 언약의 표시는?',
    options: ['할례', '안식일', '무지개', '성전'], correctIndex: 2 },
  { question: '소돔과 고모라가 멸망할 때 뒤를 돌아봐 소금기둥이 된 사람은?',
    options: ['롯의 아내', '롯의 딸', '아브라함의 아내', '롯'], correctIndex: 0 },
  { question: '바벨탑은 왜 쌓으려 했나요?',
    options: ['하늘에 닿으려고', '전쟁에 대비하려고', '왕궁을 만들려고', '하나님께 제사하려고'], correctIndex: 0 },

  // ── 출애굽 / 모세 ──────────────────────────────
  { question: '이스라엘 백성이 이집트에서 종살이한 기간은?',
    options: ['약 100년', '약 200년', '약 300년', '약 400년'], correctIndex: 3 },
  { question: '모세가 하나님을 처음 만난 곳은?',
    options: ['성전', '떨기나무 앞', '요단강가', '시내산 꼭대기'], correctIndex: 1 },
  { question: '이집트에 내린 재앙은 모두 몇 가지인가요?',
    options: ['7가지', '9가지', '10가지', '12가지'], correctIndex: 2 },
  { question: '이집트 10가지 재앙 중 마지막 재앙은?',
    options: ['메뚜기 재앙', '흑암 재앙', '장자의 죽음', '우박 재앙'], correctIndex: 2 },
  { question: '십계명이 새겨진 재료는?',
    options: ['나무판', '금판', '돌판', '은판'], correctIndex: 2 },
  { question: '광야에서 이스라엘 백성을 낮에 인도한 것은?',
    options: ['구름기둥', '불기둥', '천사', '별'], correctIndex: 0 },
  { question: '광야에서 이스라엘 백성을 밤에 인도한 것은?',
    options: ['구름기둥', '불기둥', '별', '달빛'], correctIndex: 1 },
  { question: '이스라엘 백성이 광야에서 먹은 음식 이름은?',
    options: ['보리빵', '만나', '무화과', '포도'], correctIndex: 1 },
  { question: '모세의 누나 이름은?',
    options: ['드보라', '한나', '미리암', '에스더'], correctIndex: 2 },
  { question: '모세가 십계명을 받은 산은?',
    options: ['올리브산', '갈멜산', '시온산', '시내산'], correctIndex: 3 },
  { question: '여리고 성을 함락시킨 이스라엘의 지도자는?',
    options: ['모세', '여호수아', '사무엘', '엘리야'], correctIndex: 1 },
  { question: '노아가 방주에서 내보낸 비둘기가 올리브 잎을 물고 온 것은 무엇을 의미했나요?',
    options: ['심판의 시작', '물이 빠졌다는 신호', '하나님의 분노', '비가 더 올 것이라는 경고'], correctIndex: 1 },
  { question: '모세의 형의 이름은?',
    options: ['나답', '아론', '훌', '갈렙'], correctIndex: 1 },

  // ── 사사/왕정 시대 ──────────────────────────────
  { question: '이스라엘 최초의 왕은?',
    options: ['다윗', '솔로몬', '사울', '요시야'], correctIndex: 2 },
  { question: '이스라엘에서 가장 지혜로운 왕으로 알려진 사람은?',
    options: ['다윗', '솔로몬', '히스기야', '요시야'], correctIndex: 1 },
  { question: '다윗이 쓰러뜨린 블레셋 거인의 이름은?',
    options: ['골리앗', '바알', '나발', '하만'], correctIndex: 0 },
  { question: '예루살렘 성전을 처음 지은 왕은?',
    options: ['다윗', '솔로몬', '히스기야', '느헤미야'], correctIndex: 1 },
  { question: '삼손이 사랑한 여인의 이름은?',
    options: ['에스더', '룻', '들릴라', '미리암'], correctIndex: 2 },
  { question: '이스라엘의 사사 중 여성 사사는?',
    options: ['한나', '드보라', '미리암', '훌다'], correctIndex: 1 },
  { question: '갈멜산에서 바알 선지자들과 대결한 선지자는?',
    options: ['엘리사', '이사야', '엘리야', '예레미야'], correctIndex: 2 },
  { question: '다니엘이 사자굴에 들어간 이유는?',
    options: ['왕을 모욕해서', '하나님께 기도를 계속해서', '우상 숭배를 거부해서', '도둑질해서'], correctIndex: 1 },
  { question: '선지자 엘리야를 하늘로 데려간 것은?',
    options: ['하나님의 손', '불말과 불병거', '구름', '큰 바람'], correctIndex: 1 },
  { question: '에스더가 도운 민족은?',
    options: ['이방인', '블레셋 사람', '유대인', '이집트 사람'], correctIndex: 2 },
  { question: '요나가 도망치려 한 도시의 이름은?',
    options: ['니느웨', '다시스', '예루살렘', '바벨론'], correctIndex: 1 },
  { question: '하나님께 순종해 니느웨로 간 선지자는?',
    options: ['엘리야', '요나', '이사야', '예레미야'], correctIndex: 1 },
  { question: '느헤미야가 귀환해 재건한 것은?',
    options: ['성전', '예루살렘 성벽', '다윗의 왕궁', '바벨탑'], correctIndex: 1 },
  { question: '욥이 하나님의 허락으로 시험을 받을 때 욥에게 가한 자는?',
    options: ['악한 사람들', '사탄', '천사', '이방 나라 왕'], correctIndex: 1 },
  { question: '다윗의 아들로 이스라엘을 반역한 사람은?',
    options: ['요나단', '솔로몬', '압살롬', '아도니야'], correctIndex: 2 },

  // ── 예수님의 탄생과 생애 ────────────────────────
  { question: '예수님이 태어나신 도시는 어디인가요?',
    options: ['예루살렘', '나사렛', '여리고', '베들레헴'], correctIndex: 3 },
  { question: '예수님에게 세례를 베푼 사람은?',
    options: ['베드로', '요한', '세례 요한', '사가랴'], correctIndex: 2 },
  { question: '예수님이 세례를 받은 강은?',
    options: ['유프라테스강', '요단강', '나일강', '기혼강'], correctIndex: 1 },
  { question: '예수님이 광야에서 시험받은 기간은?',
    options: ['20일', '30일', '40일', '50일'], correctIndex: 2 },
  { question: '예수님의 어머니 이름은?',
    options: ['엘리사벳', '막달라 마리아', '마리아', '마르다'], correctIndex: 2 },
  { question: '예수님의 양아버지(법적 아버지) 이름은?',
    options: ['사가랴', '요셉', '요한', '시므온'], correctIndex: 1 },
  { question: '예수님이 태어나실 때 동방박사들이 가져온 선물이 아닌 것은?',
    options: ['황금', '유향', '몰약', '은'], correctIndex: 3 },
  { question: '예수님의 첫 번째 기적은 무엇인가요?',
    options: ['물 위를 걸으심', '물을 포도주로 바꾸심', '오병이어 기적', '나사로를 살리심'], correctIndex: 1 },
  { question: '오병이어 기적에서 빵 5개와 함께 있던 것은?',
    options: ['포도주 2병', '물고기 2마리', '물고기 3마리', '과일 2개'], correctIndex: 1 },
  { question: '예수님이 십자가에 달리신 곳은?',
    options: ['베들레헴', '나사렛', '골고다', '겟세마네'], correctIndex: 2 },
  { question: '예수님이 부활하신 날은 무슨 요일인가요?',
    options: ['안식일(토요일)', '주일(일요일)', '월요일', '금요일'], correctIndex: 1 },
  { question: '예수님의 변화산에서 함께 나타난 구약 인물은?',
    options: ['아브라함과 다윗', '엘리야와 모세', '사무엘과 에녹', '이사야와 예레미야'], correctIndex: 1 },
  { question: '예수님이 부활 후 승천하신 곳은?',
    options: ['갈릴리', '베들레헴', '감람산', '성전'], correctIndex: 2 },
  { question: '예수님이 죽으신 후 무덤에 계신 기간은?',
    options: ['1일', '2일', '3일', '7일'], correctIndex: 2 },
  { question: '예수님의 부활을 가장 먼저 목격한 사람은?',
    options: ['베드로', '요한', '막달라 마리아', '야고보'], correctIndex: 2 },
  { question: '예수님이 부활 후 승천하신 것은 부활 후 며칠만인가요?',
    options: ['7일', '20일', '40일', '50일'], correctIndex: 2 },
  { question: '예수님이 기도하시다 잡히신 동산은?',
    options: ['성전 마당', '골고다', '겟세마네', '감람산'], correctIndex: 2 },
  { question: '예수님께서 물 위를 걸으신 곳은?',
    options: ['요단강', '홍해', '갈릴리 바다', '사해'], correctIndex: 2 },
  { question: '예수님의 열두 제자 중 세리(세금 징수원)였던 사람은?',
    options: ['베드로', '요한', '마태', '가룟 유다'], correctIndex: 2 },
  { question: '예수님을 배반한 제자는 누구인가요?',
    options: ['베드로', '도마', '가룟 유다', '요한'], correctIndex: 2 },
  { question: '가브리엘 천사가 마리아에게 수태고지를 전한 장소는?',
    options: ['예루살렘 성전', '나사렛', '베들레헴', '갈릴리 바다'], correctIndex: 1 },
  { question: '예수님의 12제자 중 어부였던 사람이 아닌 것은?',
    options: ['베드로', '안드레', '요한', '마태'], correctIndex: 3 },

  // ── 비유와 가르침 ───────────────────────────────
  { question: '잃어버린 양 비유에서 양은 몇 마리 중 몇 마리였나요?',
    options: ['10마리 중 1마리', '50마리 중 1마리', '100마리 중 1마리', '200마리 중 10마리'], correctIndex: 2 },
  { question: '선한 사마리아인 비유에서 강도 만난 사람을 도운 것은?',
    options: ['제사장', '레위인', '사마리아인', '유대인'], correctIndex: 2 },
  { question: '탕자의 비유에서 탕자가 돌아왔을 때 아버지가 한 것은?',
    options: ['야단쳤다', '집에 들이지 않았다', '잔치를 열었다', '용돈을 줬다'], correctIndex: 2 },
  { question: '달란트 비유에서 한 달란트를 땅에 묻은 종은 어떻게 됐나요?',
    options: ['칭찬받았다', '그냥 돌려받았다', '가진 것마저 빼앗겼다', '두 달란트를 받았다'], correctIndex: 2 },
  { question: '예수님이 가르쳐 주신 기도문(주기도문)의 첫 구절은?',
    options: ['아버지, 감사합니다', '하늘에 계신 우리 아버지', '주님, 저를 도와주세요', '주 예수여'], correctIndex: 1 },
  { question: '열 처녀 비유에서 기름을 준비한 슬기로운 처녀는 몇 명인가요?',
    options: ['3명', '5명', '7명', '10명'], correctIndex: 1 },
  { question: '씨 뿌리는 자의 비유에서 좋은 땅에 떨어진 씨는?',
    options: ['열매를 못 맺는다', '30배·60배·100배 열매를 맺는다', '새가 먹어버린다', '말라버린다'], correctIndex: 1 },
  { question: '포도나무 비유에서 예수님은 자신을 무엇이라 하셨나요?',
    options: ['포도', '포도원', '참 포도나무', '포도 농부'], correctIndex: 2 },
  { question: '가장 큰 계명은 무엇인가요?',
    options: ['살인하지 말라', '안식일을 지키라', '하나님을 사랑하고 이웃을 사랑하라', '십일조를 드리라'], correctIndex: 2 },
  { question: '예수님이 산상설교를 하신 곳은 어디인가요?',
    options: ['성전', '갈릴리 바다 위', '산', '회당'], correctIndex: 2 },
  { question: '탕자의 비유에서 형은 동생이 돌아왔을 때 어떻게 반응했나요?',
    options: ['기뻐했다', '화가 났다', '울었다', '도망갔다'], correctIndex: 1 },

  // ── 사도행전과 초대교회 ─────────────────────────
  { question: '성령이 제자들에게 임하신 날은?',
    options: ['유월절', '초막절', '오순절', '부림절'], correctIndex: 2 },
  { question: '오순절에 성령을 받은 제자들의 수는 약 몇 명인가요?',
    options: ['70명', '100명', '120명', '150명'], correctIndex: 2 },
  { question: '스테반이 돌에 맞아 죽을 때 그 자리를 찬성한 사람은?',
    options: ['베드로', '바울(사울)', '야고보', '빌립'], correctIndex: 1 },
  { question: '바울이 예수님을 만난 곳은?',
    options: ['예루살렘', '안디옥', '다메섹으로 가는 길', '아테네'], correctIndex: 2 },
  { question: '베드로가 옥에 갇혔을 때 구해준 것은?',
    options: ['다른 제자들', '천사', '로마 군인', '헤롯왕'], correctIndex: 1 },
  { question: '최초의 이방인 신자로 베드로에게 세례를 받은 사람은?',
    options: ['에디오피아 내시', '고넬료', '루디아', '빌립보 간수'], correctIndex: 1 },
  { question: '바울이 처음 선교 여행을 함께한 동반자는?',
    options: ['실라', '디모데', '바나바', '누가'], correctIndex: 2 },
  { question: '아테네 아레오바고에서 설교한 사람은?',
    options: ['베드로', '바울', '야고보', '빌립'], correctIndex: 1 },
  { question: '초대교회가 탄생한 도시는?',
    options: ['로마', '안디옥', '예루살렘', '아테네'], correctIndex: 2 },
  { question: '바울이 전도 여행 중 옥에서 찬양했을 때 일어난 일은?',
    options: ['경비병이 잠들었다', '옥문이 열리고 사슬이 풀렸다', '천사가 나타났다', '아무 일도 없었다'], correctIndex: 1 },

  // ── 서신서와 계시록 ─────────────────────────────
  { question: '"믿음, 소망, 사랑 중에 그 중의 제일은 사랑이라"는 어느 책에 나오나요?',
    options: ['갈라디아서', '에베소서', '고린도전서', '골로새서'], correctIndex: 2 },
  { question: '로마서를 쓴 사람은?',
    options: ['베드로', '요한', '바울', '야고보'], correctIndex: 2 },
  { question: '요한계시록을 기록한 사람은?',
    options: ['바울', '베드로', '요한', '야고보'], correctIndex: 2 },
  { question: '요한계시록에서 나오는 짐승의 수는?',
    options: ['444', '555', '666', '777'], correctIndex: 2 },
  { question: '야고보서에서 "행함이 없는 믿음은" 무엇이라고 했나요?',
    options: ['불완전하다', '죽은 것이다', '부족하다', '성장해야 한다'], correctIndex: 1 },
  { question: '"내게 능력 주시는 자 안에서 내가 모든 것을 할 수 있느니라"는 어느 책인가요?',
    options: ['로마서', '빌립보서', '에베소서', '골로새서'], correctIndex: 1 },
  { question: '"너희가 은혜로 구원을 받았으니 믿음으로 말미암아"는 어느 책인가요?',
    options: ['로마서', '갈라디아서', '에베소서', '빌립보서'], correctIndex: 2 },
  { question: '"하나님은 사랑이시라"는 말씀은 어느 책에 나오나요?',
    options: ['요한복음', '요한1서', '요한2서', '요한3서'], correctIndex: 1 },
  { question: '히브리서에서 "믿음은 바라는 것들의 실상이요" 이어서 나오는 말씀은?',
    options: ['바라는 것들의 증거', '보이지 않는 것들의 증거', '하나님의 말씀', '소망의 빛'], correctIndex: 1 },
  { question: '"주 안에서 항상 기뻐하라"고 말한 사람은?',
    options: ['베드로', '바울', '요한', '야고보'], correctIndex: 1 },

  // ── 성경 인물 ───────────────────────────────────
  { question: '구약의 대표적인 인내의 사람은?',
    options: ['다윗', '욥', '예레미야', '모세'], correctIndex: 1 },
  { question: '"슬피 우는 선지자"로 불리는 선지자는?',
    options: ['이사야', '아모스', '예레미야', '에스겔'], correctIndex: 2 },
  { question: '왕비가 되어 유대 민족을 구한 여인은?',
    options: ['룻', '드보라', '에스더', '한나'], correctIndex: 2 },
  { question: '솔로몬의 아버지는?',
    options: ['사울', '다윗', '아브라함', '모세'], correctIndex: 1 },
  { question: '12제자 중 예수님이 "반석"이라는 뜻으로 부른 사람은?',
    options: ['요한', '야고보', '안드레', '베드로'], correctIndex: 3 },
  { question: '엘리야의 뒤를 이은 선지자는?',
    options: ['이사야', '엘리사', '에스겔', '호세아'], correctIndex: 1 },
  { question: '베드로의 원래 이름은?',
    options: ['시몬', '요한', '안드레', '사울'], correctIndex: 0 },
  { question: '이삭의 아버지는?',
    options: ['야곱', '아브라함', '모세', '노아'], correctIndex: 1 },
  { question: '예수님의 공생애 기간은 약 몇 년인가요?',
    options: ['1년', '2년', '3년', '5년'], correctIndex: 2 },
  { question: '예수님이 공생애를 시작하신 나이는?',
    options: ['25세', '28세', '30세', '33세'], correctIndex: 2 },

  // ── 성경 통계와 상식 ────────────────────────────
  { question: '성경은 구약과 신약을 합쳐 모두 몇 권인가요?',
    options: ['64권', '65권', '66권', '68권'], correctIndex: 2 },
  { question: '구약성경은 몇 권인가요?',
    options: ['27권', '34권', '39권', '44권'], correctIndex: 2 },
  { question: '신약성경은 몇 권인가요?',
    options: ['20권', '27권', '30권', '36권'], correctIndex: 1 },
  { question: '성경의 첫 번째 책은?',
    options: ['신명기', '출애굽기', '창세기', '레위기'], correctIndex: 2 },
  { question: '신약성경의 첫 번째 책은?',
    options: ['마가복음', '요한복음', '마태복음', '누가복음'], correctIndex: 2 },
  { question: '성경의 마지막 책은?',
    options: ['히브리서', '유다서', '요한계시록', '요한3서'], correctIndex: 2 },
  { question: '성경에서 가장 오래 산 사람은? (969세)',
    options: ['노아', '아담', '므두셀라', '에녹'], correctIndex: 2 },
  { question: '성경에서 가장 짧은 구절로 알려진 것은?',
    options: ['주를 사랑하라', '예수께서 우셨더라', '기도하라', '평안할지어다'], correctIndex: 1 },
  { question: '시편을 주로 쓴 사람은?',
    options: ['모세', '다윗', '솔로몬', '아삽'], correctIndex: 1 },
  { question: '"하나님이 세상을 이처럼 사랑하사"는 성경 어디에 있나요?',
    options: ['마태복음 3장 16절', '요한복음 3장 16절', '로마서 3장 16절', '시편 23장 1절'], correctIndex: 1 },
  { question: '베드로의 원래 직업은?',
    options: ['세금 징수원', '목수', '어부', '의사'], correctIndex: 2 },
  { question: '사도 바울의 원래 이름은?',
    options: ['시몬', '사울', '야고보', '마가'], correctIndex: 1 },
  { question: '성경에서 가장 긴 책은?',
    options: ['창세기', '이사야', '시편', '예레미야'], correctIndex: 2 },
  { question: '성경에서 가장 짧은 책은?',
    options: ['요한2서', '요한3서', '오바댜', '빌레몬서'], correctIndex: 1 },
  { question: '이스라엘 광야에서 이스라엘 백성이 메추라기와 함께 먹은 것은?',
    options: ['빵', '만나', '과일', '채소'], correctIndex: 1 },

  // ── 교회와 예배 상식 ────────────────────────────
  { question: '교회에서 성찬식에 사용하는 것은?',
    options: ['물과 소금', '떡과 포도주(포도즙)', '꿀과 우유', '밀가루와 물'], correctIndex: 1 },
  { question: '오순절 성령 강림 이후 하루에 몇 명이 세례를 받았나요?',
    options: ['약 1000명', '약 2000명', '약 3000명', '약 5000명'], correctIndex: 2 },
  { question: '주기도문의 마지막 구절은?',
    options: ['아멘', '나라와 권세와 영광이 아버지께 영원히 있사옵나이다 아멘', '우리를 악에서 구하옵소서', '뜻이 하늘에서 이루어진 것같이'], correctIndex: 1 },
  { question: '십계명에서 "살인하지 말라"는 몇 번째 계명인가요?',
    options: ['5번째', '6번째', '7번째', '8번째'], correctIndex: 1 },
  { question: '십계명에서 "안식일을 기억하여 거룩하게 지키라"는 몇 번째 계명인가요?',
    options: ['3번째', '4번째', '5번째', '6번째'], correctIndex: 1 },
  { question: '세례 요한의 부모는?',
    options: ['요셉과 마리아', '사가랴와 엘리사벳', '아비야와 나오미', '요아김과 안나'], correctIndex: 1 },
  { question: '사도 바울이 쓴 것으로 알려진 책이 아닌 것은?',
    options: ['로마서', '고린도전서', '요한계시록', '갈라디아서'], correctIndex: 2 },
  { question: '"여호와는 나의 목자시니 내게 부족함이 없으리로다"는 시편 몇 편인가요?',
    options: ['시편 1편', '시편 23편', '시편 51편', '시편 100편'], correctIndex: 1 },
  { question: '예수님이 승천하시기 전 제자들에게 주신 명령은?',
    options: ['성전을 세우라', '가서 모든 민족을 제자로 삼으라', '안식일을 지키라', '율법을 가르치라'], correctIndex: 1 },
  { question: '성령의 아홉 가지 열매 중 가장 먼저 나오는 것은?',
    options: ['기쁨', '사랑', '화평', '오래 참음'], correctIndex: 1 },
  { question: '예수님이 탄생하실 때 아기 예수님이 누운 곳은?',
    options: ['왕궁', '여관 방', '마구간 구유', '회당'], correctIndex: 2 },
  { question: '성경에서 "사랑은 오래 참고 사랑은 온유하며"는 어느 책인가요?',
    options: ['에베소서 5장', '고린도전서 13장', '요한1서 4장', '로마서 12장'], correctIndex: 1 },
];

// ── 성경 넌센스 퀴즈 문제 은행 ────────────────────────────────────
const NONSENSE_QUIZ_DATA = [

  // 성경 인물 특징
  { question: '엄마 뱃속에서 태어나지 않은 사람은?', options: ['노아', '아담과 하와', '모세', '아브라함'], correctIndex: 1, enabled: true },
  { question: '성경 인물 중에서 장사를 제일 잘하는 사람은?', options: ['사라', '룻', '드보라', '한나'], correctIndex: 0, enabled: true },
  { question: '성경 인물 중 장사를 제일 못하는 사람은?', options: ['모세', '요담', '사가랴', '바울'], correctIndex: 2, enabled: true },
  { question: '성경 인물 중 엄마들이 가장 좋아하고 친한 사람은?', options: ['마리아', '도마', '베드로', '요한'], correctIndex: 1, enabled: true },
  { question: '성경 인물 중 거지 근성이 제일 많은 사람은?', options: ['삭개오', '막달라 마리아', '바디매오', '나오미'], correctIndex: 1, enabled: true },
  { question: '성경 인물 중 귀가 제일 밝은 사람은?', options: ['사무엘', '들릴라', '엘리야', '미리암'], correctIndex: 1, enabled: true },
  { question: '성경 인물 중 미루기를 제일 잘하는 사람은?', options: ['요담', '요나', '기드온', '삼손'], correctIndex: 0, enabled: true },
  { question: '성경 인물 중 옷을 제일 잘 입는 사람은?', options: ['에스더', '솔로몬', '요셉', '입다'], correctIndex: 3, enabled: true },
  { question: '성경 인물 중 시험만 치면 100점 받는 사람은?', options: ['다니엘', '솔로몬', '미리암', '사무엘'], correctIndex: 2, enabled: true },
  { question: '성경 인물 중 수학을 제일 못하는 사람은?', options: ['모세', '셈', '엘리사', '발람'], correctIndex: 0, enabled: true },
  { question: '성경 인물 중 항상 자신을 봐 주기를 원하는 사람은?', options: ['삭개오', '바울', '바라바', '나사로'], correctIndex: 2, enabled: true },
  { question: '보통 사람보다 손이 하나 더 있는 사람은?', options: ['골리앗', '삼손', '기드온', '엘리사'], correctIndex: 1, enabled: true },
  { question: '뼈를 깎는 고통을 최초로 느낀 사람은?', options: ['욥', '아담', '야곱', '다니엘'], correctIndex: 1, enabled: true },
  { question: '아담과 하와 중 누구의 몸무게가 더 가벼웠을까?', options: ['하와', '아담 (갈비뼈가 없으니까)', '둘 다 같다', '알 수 없다'], correctIndex: 1, enabled: true },
  { question: '성경에서 딸을 가장 많이 낳은 여인은?', options: ['레아', '막달라 마리아', '라헬', '드보라'], correctIndex: 1, enabled: true },
  { question: '성경 인물 중 응답을 제일 잘 받는 사람은?', options: ['엘리야', '다니엘', '다비다', '베드로'], correctIndex: 2, enabled: true },
  { question: '성경에서 수학을 제일 잘 할 것 같은 사람은?', options: ['솔로몬', '셈', '다니엘', '에스라'], correctIndex: 1, enabled: true },
  { question: '소경 바디매오와 다혈질 베드로가 싸웠다. 누가 이겼을까?', options: ['베드로', '바디매오 (뵈는 게 없어서)', '무승부', '둘 다 다쳤다'], correctIndex: 1, enabled: true },
  { question: '성경 인물 중 서예를 가장 잘 했던 사람은?', options: ['모세', '솔로몬', '붓 (함의 아들)', '에스라'], correctIndex: 2, enabled: true },
  { question: '성경의 첫 글자는 무엇입니까?', options: ['태', '성', '창', '하'], correctIndex: 1, enabled: true },
  { question: '성경 인물 중 머리카락이 세 개밖에 없는 사람은?', options: ['삼손', '엘리사', '모세 (모세 = 세 개)', '나아만'], correctIndex: 2, enabled: true },
  { question: '성경 인물 중 아무리 먹어도 살이 안 찌는 여자는?', options: ['한나', '마르다', '에스더', '룻'], correctIndex: 1, enabled: true },
  { question: '성경 인물 중 다리가 다섯 개인 사람은?', options: ['삼손', '골리앗', '다리오', '기드온'], correctIndex: 2, enabled: true },
  { question: '나는 닭을 싫어합니다. 닭만 봐도 지겹습니다. 나는?', options: ['마태', '요한', '베드로', '야고보'], correctIndex: 2, enabled: true },
  { question: '힘이 세어서 힘으로 죽은 사람은?', options: ['골리앗', '헤라클레스', '삼손', '압살롬'], correctIndex: 2, enabled: true },
  { question: '나무 타기를 잘하는 성경 인물은?', options: ['삭개오', '다윗', '압살롬', '요나'], correctIndex: 0, enabled: true },
  { question: '사람에게서 태어나서 다시 짐승에게서 태어난 사람은?', options: ['다니엘', '요나', '삼손', '에녹'], correctIndex: 1, enabled: true },
  { question: '가정주부와 가장 친한 성경 인물은? (힌트: 주방용품)', options: ['마리아', '도마', '에스더', '한나'], correctIndex: 1, enabled: true },
  { question: '성경 인물 중 드라이버와 함께 기계를 조이는 것은?', options: ['스패너', '볼트', '나사로', '렌치'], correctIndex: 2, enabled: true },

  // 성경책 이름 넌센스
  { question: '성경 중 읽기가 제일 힘든 성경은?', options: ['레위기', '민수기', '에스라', '역대기'], correctIndex: 2, enabled: true },
  { question: '에스라보다 더 읽기 힘든 성경은?', options: ['레위기', '에스더', '역대기', '민수기'], correctIndex: 1, enabled: true },
  { question: '마귀들이 좋아하는 성경책은?', options: ['요한계시록', '골로새서 (골내소서)', '에베소서', '로마서'], correctIndex: 1, enabled: true },
  { question: '부모님께 잘못했을 때 읽어야 하는 성경은?', options: ['갈라디아서', '잠언', '빌립보서 (빌었으니까)', '시편'], correctIndex: 2, enabled: true },
  { question: '아기를 낳기를 원하는 사람이 읽어야 하는 신구약은?', options: ['창세기, 요한복음', '에스라, 에베소서', '룻기, 마태복음', '잠언, 사도행전'], correctIndex: 1, enabled: true },
  { question: '또 아기를 낳기를 원하는 사람이 꼭 읽어야 하는 성경은?', options: ['에베소서', '에스라', '에스더 (에 더 쓰라!)', '에스겔'], correctIndex: 2, enabled: true },
  { question: '이혼하고 싶은 사람들이 읽는 성경은?', options: ['고린도전서', '갈라디아서', '로마서', '히브리서'], correctIndex: 1, enabled: true },
  { question: '부부 싸움 후 바로 읽으면 안 되는 성경은?', options: ['에베소서', '로마서', '갈라디아서 (갈라지니까)', '빌립보서'], correctIndex: 2, enabled: true },
  { question: '어린이들이 가장 좋아하는 성경책은?', options: ['잠언', '시편', '전도서', '아가서'], correctIndex: 3, enabled: true },
  { question: '읽으면 잠이 쏟아지는 성경은?', options: ['전도서', '잠언', '시편', '민수기'], correctIndex: 1, enabled: true },
  { question: '여름에 꼭 읽어야 하는 성경책은?', options: ['나훔', '오바댜 (오! 바다!)', '하박국', '말라기'], correctIndex: 1, enabled: true },
  { question: '가장 아름다운 노래가 들어 있는 성경책은?', options: ['아가서', '시편', '미가서 (미가=미가)', '하박국'], correctIndex: 2, enabled: true },
  { question: '신약과 구약 사이에 있는 것은?', options: ['중간기', '공백', '과', '성간'], correctIndex: 2, enabled: true },
  { question: '교인들이 가장 좋아하는 구구단은?', options: ['2×9=18', '3×9=27 (구약39, 신약27)', '4×9=36', '6×9=54'], correctIndex: 1, enabled: true },
  { question: '잠잘 때 듣는 말은?', options: ['전도서', '시편', '잠언', '룻기'], correctIndex: 2, enabled: true },
  { question: '목회자가 아이를 낳게 해달라고 읽는 성경책은?', options: ['창세기', '룻기', '에베소서', '출애굽기'], correctIndex: 2, enabled: true },

  // 성경 지명/장소
  { question: '성경에 옷장사를 하면 안 되는 공원이 있는데 어디인가?', options: ['갈릴리', '에덴동산', '가나안', '예루살렘'], correctIndex: 1, enabled: true },
  { question: '시냇물이 졸졸졸 흐르는 산의 이름은?', options: ['갈멜산', '올리브산', '헤르몬산', '시내산'], correctIndex: 3, enabled: true },
  { question: '살아서는 절대로 건널 수 없는 강은?', options: ['기혼강', '유브라데강', '요단강', '기손강'], correctIndex: 2, enabled: true },
  { question: '혼인 후에 흐르는 강은?', options: ['유브라데강', '요단강', '기혼강', '기손강'], correctIndex: 2, enabled: true },
  { question: '이탈리아 수도에 서 있다를 세 글자로 줄이면?', options: ['이탈리아', '사도행전', '로마서', '갈라디아서'], correctIndex: 2, enabled: true },
  { question: '성경의 성 중에서 가장 작은 성은?', options: ['여리고성', '아이성', '베들레헴', '나인성'], correctIndex: 1, enabled: true },
  { question: '천국과 지옥 사이에 있는 것은?', options: ['연옥', '하늘', '과 (신약과 구약)', '공간'], correctIndex: 2, enabled: true },
  { question: '발렌타인데이 때 가장 인기있는 동네는?', options: ['에덴', '베들레헴', '가나', '갈릴리'], correctIndex: 2, enabled: true },
  { question: '역도 선수들이 좋아하는 탑은?', options: ['실로암탑', '바벨탑', '다윗탑', '안디옥탑'], correctIndex: 1, enabled: true },
  { question: '강하고의 반대말, 약하고의 비슷한 말은?', options: ['가나안', '갈릴리', '여리고', '예루살렘'], correctIndex: 2, enabled: true },
  { question: '농구 선수들이 좋아하는 성경 지명은?', options: ['길보아', '가드 (골리앗 고향)', '갈멜', '가나'], correctIndex: 1, enabled: true },
  { question: '세계 최초의 부실공사는?', options: ['바벨탑', '솔로몬 성전', '노아의 방주', '여리고성'], correctIndex: 3, enabled: true },
  { question: '많기도 하고 적기도 한 도시 이름은?', options: ['가나', '다소', '길보아', '에베소'], correctIndex: 1, enabled: true },
  { question: '아무리 돈이 많아도 평생 한번도 못 가는 곳은?', options: ['예루살렘', '시온', '천국과 지옥', '에덴동산'], correctIndex: 2, enabled: true },
  { question: '세계 최초로 지도를 작성한 사람은? (힌트: 오줌으로 땅에 그렸으므로)', options: ['노아', '아브라함', '가인', '모세'], correctIndex: 2, enabled: true },
  { question: '성경에서 흑인이 한 명도 없었던 곳은?', options: ['에디오피아', '애굽', '힌놈의 골짜기 (흰놈만 있어서)', '가나안'], correctIndex: 2, enabled: true },

  // 자연/동물
  { question: '하나님이 노아에게 주신 개 이름은?', options: ['충견', '진돗개', '무지개', '에덴개'], correctIndex: 2, enabled: true },
  { question: '가장 오랫동안 물속에서 잠수한 사람은? (3일)', options: ['모세', '베드로', '요나', '빌립'], correctIndex: 2, enabled: true },
  { question: '가짜로 내리는 비는?', options: ['산성비', '소나기', '사이비', '폭우'], correctIndex: 2, enabled: true },
  { question: '뜨겁지는 않지만 따가운 불은?', options: ['성막의 불', '솔로몬의 등불', '가시덤불', '제단의 불'], correctIndex: 2, enabled: true },
  { question: '성경에서 등에 산봉우리를 지고 다니는 동물은?', options: ['코끼리', '말', '곰', '낙타'], correctIndex: 3, enabled: true },
  { question: '땅으로 기어다니는 부정한 제비는?', options: ['솔개', '독수리', '족제비', '참새'], correctIndex: 2, enabled: true },
  { question: '어릴 때는 울지 못하고 어른이 돼서야 우는 동물은?', options: ['사자', '개구리', '나귀', '소'], correctIndex: 1, enabled: true },
  { question: '공룡이 멸종한 이유는?', options: ['빙하기 때문에', '운석 충돌 때문에', '노아의 방주에 들어갈 수 없어서', '홍수로 익사해서'], correctIndex: 2, enabled: true },
  { question: '하늘에 있는 개 네 마리의 이름은?', options: ['사자개, 무지개, 번개, 안개', '솔개, 무지개, 번개, 안개', '솔개, 무지개, 폭개, 안개', '솔개, 호개, 번개, 안개'], correctIndex: 1, enabled: true },
  { question: '꽃 백송이를 모아서 만든 꽃은?', options: ['장미꽃', '국화꽃', '백합꽃', '진달래'], correctIndex: 2, enabled: true },
  { question: '동풍이 불면 엘리사 선지자의 머리는 어느 방향으로 날리는가?', options: ['동쪽', '서쪽', '남쪽', '날리지 않는다 (대머리)'], correctIndex: 3, enabled: true },
  { question: '선지자 중 바닷가에서 수영해도 머리가 젖지 않은 사람은?', options: ['엘리야', '이사야', '엘리사 (대머리)', '예레미야'], correctIndex: 2, enabled: true },
  { question: '바늘구멍으로 빠져나갈 수 있는 것 중 제일 큰 것은?', options: ['코끼리', '고래', '낙타', '하마'], correctIndex: 2, enabled: true },
  { question: '엘리사 선지자가 전혀 걱정하지 않는 병은?', options: ['나병', '간질병', '탈모증 (이미 대머리)', '소경'], correctIndex: 2, enabled: true },

  // 수수께끼/언어유희
  { question: '신약과 구약을 합하면 66권, 성경은 모두 몇 자인가?', options: ['66자', '2자 (성-경)', '6자', '모두 합쳐야 알 수 있다'], correctIndex: 1, enabled: true },
  { question: '성경에서 가장 짧은 장은 시편 117편, 가장 두꺼운 장은?', options: ['시편 119편', '요한계시록', '겉장', '모든 장'], correctIndex: 2, enabled: true },
  { question: '천사를 숫자로 표현하면 1004, 사람은?', options: ['1000', '1003 (천사보다 조금 못해서)', '1004', '1002'], correctIndex: 1, enabled: true },
  { question: '하늘나라의 전화번호는?', options: ['1004', '777-7777', '66-3927 (성경 66권, 구약 39권, 신약 27권)', '333-3333'], correctIndex: 2, enabled: true },
  { question: '인류 최초의 쓰레기는?', options: ['노아 방주의 쓰레기', '선악과 먹고 남은 것', '바벨탑 건축 쓰레기', '이집트 파피루스'], correctIndex: 1, enabled: true },
  { question: '"천사가 나타나고 악마는 사라져라"를 네 자로 줄이면?', options: ['천사보호령', '성령강림해', '나짠 너뿅', '평화가득해'], correctIndex: 2, enabled: true },
  { question: '새 두 마리를 두 글자로 표현하면?', options: ['독수리', '이새 (다윗의 아버지)', '두마리', '비둘기'], correctIndex: 1, enabled: true },
  { question: '"팔아라"의 반대말은?', options: ['살라', '사라', '구라', '빌라'], correctIndex: 1, enabled: true },
  { question: '"너 먼저 골라라"를 세 글자로 말하면?', options: ['먼저너라', '골라라라', '니골라', '너골라'], correctIndex: 2, enabled: true },
  { question: '말이 사는 집을 한자로 쓰면?', options: ['마태', '마가', '마음', '마당'], correctIndex: 1, enabled: true },
  { question: '"죽을래"의 반대말은?', options: ['삶래', '살래 (포로기 이후의 레위 제사장)', '살아라', '생존래'], correctIndex: 1, enabled: true },
  { question: '혼인 전은 미혼, 혼인 후의 상태는?', options: ['결혼', '유혼', '기혼 (에덴동산의 강)', '완혼'], correctIndex: 2, enabled: true },
  { question: '"안의 해"를 다른 말로 표현하면?', options: ['내일', '내해', '아내', '속해'], correctIndex: 2, enabled: true },
  { question: '두 편이 싸울 때 자기 쪽의 반대편을 두 글자로?', options: ['상대', '적군', '남편', '반대'], correctIndex: 2, enabled: true },
  { question: '10원 중에 하나를 뺀 것을 무엇이라 하는가?', options: ['적선', '십일조', '구원', '헌금'], correctIndex: 2, enabled: true },
  { question: '하나님의 사무를 보는 것을 다른 말로 표현하면?', options: ['사도행전', '사무엘', '사무소', '신사'], correctIndex: 1, enabled: true },
  { question: '옷이나 물건을 넣어두는 상자를 한 글자로 말하면?', options: ['박', '통', '함 (노아의 아들)', '짐'], correctIndex: 2, enabled: true },
  { question: '서예가들의 필기구는? (성경 인물 이름)', options: ['연필', '붓 (함의 셋째 아들)', '먹', '벼루'], correctIndex: 1, enabled: true },
  { question: '미리 다 아는 여자는?', options: ['드보라', '훌다', '미리암 (모세의 누이)', '에스더'], correctIndex: 2, enabled: true },
  { question: '"누구냐"의 이북 사투리는?', options: ['고인물', '너인가', '누기오 (구레네 인)', '누기야'], correctIndex: 2, enabled: true },
  { question: '오직 한 글자로 동서남북을 가리키는 한자는?', options: ['中 (중)', '方 (방)', '十 (십자가)', '方位 (방위)'], correctIndex: 2, enabled: true },
  { question: '선의 반대는 악이다. 미소의 반대는?', options: ['슬픔', '울음', '당기소', '찡그림'], correctIndex: 2, enabled: true },
  { question: '"아름다운 노래"는 무엇인가? (성경책 이름)', options: ['아가서', '시편', '미가서', '하박국'], correctIndex: 2, enabled: true },

  // 인물 일화
  { question: '예수님과 석가모니의 가장 큰 차이점은?', options: ['가르침', '기적', '헤어스타일', '태어난 장소'], correctIndex: 2, enabled: true },
  { question: '예수님 아버지 요셉이 즐겨 부른 노래는?', options: ['구약을 사랑해', '나의 아들아', '사랑하는 마리아', '요람 속에서'], correctIndex: 2, enabled: true },
  { question: '하나님이 실수로 창조한 산은?', options: ['한라산', '북한산', '아차산', '설악산'], correctIndex: 2, enabled: true },
  { question: '기적을 가장 많이 듣고 본 사람은?', options: ['예수님 제자들', '모세', '엘리야', '열차 기관사'], correctIndex: 3, enabled: true },
  { question: '교회의 제일 높은 곳에 있는 것은?', options: ['종탑', '십자가', '피뢰침', '종'], correctIndex: 2, enabled: true },
  { question: '인류 최초의 동물원은?', options: ['에덴동산', '노아의 방주', '솔로몬 왕궁', '애굽 왕궁'], correctIndex: 1, enabled: true },
  { question: '석유 파동을 제일 싫어하는 사람은?', options: ['이스라엘 백성', '바로의 군대', '미련한 다섯 처녀', '열 명의 나병환자'], correctIndex: 2, enabled: true },
  { question: '세계 최초의 장발족은?', options: ['삼손', '압살롬', '나실인', '에서'], correctIndex: 2, enabled: true },
  { question: '9계명(거짓증거 하지 말라)을 한 번도 어기지 않은 사람은?', options: ['노아', '아브라함', '다윗', '벙어리'], correctIndex: 3, enabled: true },
  { question: '인류 최초로 기구를 통해 하늘을 날은 사람은?', options: ['에녹', '에스겔', '엘리야', '이사야'], correctIndex: 2, enabled: true },
  { question: '인류 최초로 하늘을 날은 사람은? (라이트 형제 아님)', options: ['엘리야', '에스겔', '에녹', '이사야'], correctIndex: 2, enabled: true },
  { question: '돌아온 탕자를 제일 싫어하는 것은?', options: ['형', '아버지', '살찐 송아지', '동네 사람들'], correctIndex: 2, enabled: true },
  { question: '이삭(곡식 이삭)을 가장 좋아했던 여자는?', options: ['라헬', '리브가', '룻', '드보라'], correctIndex: 2, enabled: true },
  { question: '인류 최초로 수술을 받은 사람은?', options: ['욥', '야곱', '아담 (갈비뼈 수술)', '삼손'], correctIndex: 2, enabled: true },
  { question: '세계 최초의 소방수 세 사람은?', options: ['엘리야, 엘리사, 나아만', '모세, 아론, 미리암', '사드락, 메삭, 아벳느고', '다니엘, 하나냐, 미사엘'], correctIndex: 2, enabled: true },
  { question: '전 인류의 1/4을 죽인 사람은?', options: ['노아', '바로', '가인', '헤롯'], correctIndex: 2, enabled: true },
  { question: '태어나면서부터 배를 타고 다닌 사람은?', options: ['노아', '요나', '모세 (바구니 배)', '빌립'], correctIndex: 2, enabled: true },
  { question: '세계 최장기 잠수 기록을 세운 사람은? (3일)', options: ['노아', '모세', '요나', '베드로'], correctIndex: 2, enabled: true },
  { question: '미니스커트를 제일 먼저 입은 사람은?', options: ['에스더', '리브가', '하와 (나뭇잎으로)', '막달라 마리아'], correctIndex: 2, enabled: true },
  { question: '세계 최초로 가죽치마를 입은 사람은?', options: ['노아', '아담과 하와', '아브라함', '모세'], correctIndex: 1, enabled: true },
  { question: '인류 최초의 동거 생활을 시작한 사람은?', options: ['노아와 부인', '아브라함과 사라', '아담과 하와', '이삭과 리브가'], correctIndex: 2, enabled: true },
  { question: '허수아비가 옷을 벗으면 무엇이 되나?', options: ['알몸', '막대기', '십자가', '나무'], correctIndex: 2, enabled: true },
  { question: '세계에서 가장 좋은 만병통치약은?', options: ['생명수', '말씀', '신약 구약', '기도'], correctIndex: 2, enabled: true },
  { question: '천국에 가기 위해 제일 먼저 해야 할 일은?', options: ['세례를 받아야 한다', '죽어야 한다', '기도해야 한다', '헌금해야 한다'], correctIndex: 1, enabled: true },
  { question: '벌 중에 가장 무서운 벌은?', options: ['말벌', '꿀벌', '천벌', '땡벌'], correctIndex: 2, enabled: true },
  { question: '항상 땅땅거리며 사는 사람은?', options: ['농부', '지주', '온유한 자 (땅을 기업으로)', '부자'], correctIndex: 2, enabled: true },
  { question: '돌이켜 오는 개는?', options: ['진돗개', '삽살개', '회개', '잡종'], correctIndex: 2, enabled: true },
  { question: '오른쪽에 있는 상의 이름은?', options: ['밥상', '제단', '우상', '평상'], correctIndex: 2, enabled: true },
  { question: '선지국을 먹는 사람을 무엇이라 하는가?', options: ['고기자', '음식자', '선지자', '냄비자'], correctIndex: 2, enabled: true },
  { question: '등산가들이 부르는 주제가는?', options: ['시온의 영광이 빛나는 아침', '주 안에 있는 나에게', '저 높은 곳을 향하여', '아 하나님의 은혜로'], correctIndex: 2, enabled: true },
  { question: '합기도는 왜 기도로 시작하는가?', options: ['창시자가 기독교인이라서', '시합 전 기도가 의무라서', '합기도 이름에 기도가 있으므로', '안전을 위해서'], correctIndex: 2, enabled: true },
  { question: '교회에 다니는 사람들이 싫어하는 벌레는?', options: ['바퀴벌레', '모기', '무당벌레', '파리'], correctIndex: 2, enabled: true },
  { question: '인간은 신을 점점 멀리하고 있다고 외치는 사람은?', options: ['목사님', '선지자', '고무신 장사', '신발 장수'], correctIndex: 2, enabled: true },
  { question: '사람들이 제일 보기 싫어하는 귀는?', options: ['토끼귀', '당나귀귀', '마귀', '박쥐귀'], correctIndex: 2, enabled: true },
  { question: '예수님을 찬양하는 나무는? (나는 길이요)', options: ['종려나무', '올리브나무', '가로수', '감람나무'], correctIndex: 2, enabled: true },
  { question: '아담과 아담 이후 사람의 차이는?', options: ['언어 능력', '지능 수준', '배꼽', '사고능력'], correctIndex: 2, enabled: true },
  { question: '버스 급정거 시 신실한 청년이 할머니를 껴안으며 하는 기도는?', options: ['주여 도와주소서', '하나님 감사합니다', '주여 시험에 들지 않게 하옵소서', '주여 뜻대로 하옵소서'], correctIndex: 2, enabled: true },
  { question: '버스 급정거 시 청년이 아가씨를 껴안으며 하는 기도는?', options: ['주여 시험에 들지 않게 하옵소서', '주여 뜻대로 하옵소서', '주여 구원하소서', '주여 감사합니다'], correctIndex: 1, enabled: true },
  { question: '설교를 못하는 목사님의 설교가 길어도 교인 시선이 강단을 안 떠나는 이유는?', options: ['말씀이 은혜로워서', '잠이 들어서', '시계가 목사님 뒤에 있어서', '기도하느라'], correctIndex: 2, enabled: true },
  { question: '고난당하는 사람에게 희망을 주는 소리는?', options: ['찬양소리', '기도소리', '기적소리', '종소리'], correctIndex: 2, enabled: true },
  { question: '온몸이 근지러워지는 노래는?', options: ['아리랑', '징글벨', '할렐루야', '어메이징그레이스'], correctIndex: 1, enabled: true },
  { question: '하와가 아침에 눈을 뜨면 아담의 옆구리를 만지는 이유는?', options: ['사랑해서', '아담이 아파서', '갈비 (다른 여자 만들까봐)', '아담을 깨우려고'], correctIndex: 2, enabled: true },
  { question: '노아가 방주에서 낚시를 했는데 몇 마리 잡았을까?', options: ['0마리', '2마리 (지렁이가 두 마리뿐)', '12마리', '무수히 많이'], correctIndex: 1, enabled: true },
  { question: '아담의 키가 작은 이유는?', options: ['영양 부족이라서', '흙으로 만들어서', '아담해서 (아담하다=작다)', '채소만 먹어서'], correctIndex: 2, enabled: true },
  { question: '지옥에 간 부자가 "나는 10원 적선한 적 있다"고 하자 하나님의 대답은?', options: ['거짓말하지 말라', '그래도 안 된다', '10원을 도로 주어 지옥으로 보내라', '믿음이 없었다'], correctIndex: 2, enabled: true },
  { question: '예수님께서 부활하신 후 여자들에게 제일 먼저 나타나신 이유는?', options: ['여자들이 먼저 무덤에 왔으므로', '제자들이 도망가서', '예수님도 여자들이 입이 싼 것을 아셨다', '율법에 따라서'], correctIndex: 2, enabled: true },
  { question: '교인이 절을 찾지 않는 일은?', options: ['이단행위', '신앙위반', '불가피한 일', '신앙포기'], correctIndex: 2, enabled: true },
  { question: '천국에 간 사람이 제일 좋아하는 책은?', options: ['성경', '시편', '생명책', '복음서'], correctIndex: 2, enabled: true },
  { question: '하나님이 인간을 흙으로 만든 증거는?', options: ['흙냄새가 나서', '열받으면 굳어진다', '물을 좋아해서', '흙빛 피부라서'], correctIndex: 1, enabled: true },
  { question: '천사의 반댓말은?', options: ['악마', '사탄', '4001', '지옥사자'], correctIndex: 2, enabled: true },
  { question: '천국과 지옥은 어떤 사람이 가는가?', options: ['착한 사람, 나쁜 사람', '믿는 사람, 안 믿는 사람', '죽은 사람', '기도한 사람, 안 한 사람'], correctIndex: 2, enabled: true },
  { question: '"병든 자여 다 내게로 오라"고 말한 사람은?', options: ['예수님', '의사', '엿장사', '약사'], correctIndex: 2, enabled: true },
  { question: '넓고 빨간 바다의 이름은?', options: ['지중해', '홍해', '갈릴리 바다', '사해'], correctIndex: 1, enabled: true },
  { question: '세계 최초의 베개는?', options: ['나무베개', '돌베개 (야곱)', '흙베개', '풀베개'], correctIndex: 1, enabled: true },
  { question: '이 세상에서 제일 나이 어린 왕은?', options: ['요아스', '웃시야', '느부갓네살왕 (네 살)', '히스기야'], correctIndex: 2, enabled: true },
  { question: '이 세상에서 제일 빨리 왕이 된 사람은?', options: ['다윗', '솔로몬', '바로왕', '사울'], correctIndex: 2, enabled: true },
  { question: '자기 물건이 생기면 모아서 잘 넣어두는 사람은?', options: ['노아', '솔로몬', '함 (상자=함)', '야곱'], correctIndex: 2, enabled: true },
  { question: '성경의 장발족 선지자는?', options: ['삼손', '압살롬', '나실인', '에서'], correctIndex: 2, enabled: true },
  { question: '아이를 낳게 해달라고 100일 기도드리는 여자는?', options: ['한나', '라헬', '애원한 여자', '사라'], correctIndex: 2, enabled: true },

];
